### ISSUE TITLE
reconstruct_from_listmode is incomplete

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#101]
As mentioned in #95 the `reconstruct_from_listmode` doesn't include attenuation. I know see it doesn't include randoms either. This is going to be the main demo that people would use to reconstruct data from the mMR, so it needs to be complete.

Also, default num_subsets is too low (which will mean the reconstructed image is not converged enough). I think it make more sense to use 21 subsets and 1 iteration as default. will be faster and more converged.

**Comment by evgueni-ovtchinnikov** [comment]
I got this error message when I used 12 subsets:
Number of subsets is such that subsets will be very unbalanced.\nNumber of view
grams in each subset would be:\n{66, 72, 72, 66, 60, 60, 60, 60, 60, 60, 60, 60}
\n\nEither reduce the number of symmetries used by the projector, or\nchange the
 number of subsets. It usually should be a divisor of\n252/4 (or if that's not a
n integer, a divisor of 252/2 or 252).\n\nOSMAPOSL cannot handle this.

Which is why I reduced to 2 subsets

**Comment by KrisThielemans** [comment]
yeah sure. It has to be a divisor of 252/4 for the mMR. 21 would be good. 12 isn't. sorry.

this might need documenting somewhere, but hopefully the above error is clear enough (?)

**Comment by evgueni-ovtchinnikov** [comment]
reconstruction from listmode demo with attenuation, ecat8 normalisation and randoms added
