### ISSUE TITLE
show_3D_array indices

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#177]
I see the following in the doc
```
index     : z-slices index (1-based), either Python list or string of the form
          : 'a, b-c, ...', where 'b-c' is decoded as 'b, b+1, ..., c';
```
this is rather non-python or even matlab. do we actually need this? I can do
```python
show_3D_array(image[range(5,10),:,:])
```
and similar in Matlab. I find it risky to have 1-based indices suddenly.

**Comment by evgueni-ovtchinnikov** [comment]
needs to be discussed, so far i was using 1-based indices in all dialogues

also, matlab range function is completely different, and we wanted to have our matlab scripts as close to python's as reasonably possible

to remind you, some time ago i raised a similar issue of xy axes orientation in plots, which is at present different in matlab and python, but no conclusion was reached

**Comment by evgueni-ovtchinnikov** [comment]
Closed by bac02fabd39570fc6b77bf75c0eebdd01b04fb06

**Comment by DANAJK** [comment]
With regards to the comment above about:
`show_3D_array(image[range(5,10),:,:])`
I think this is Python 2.x only as `range` no longer returns a list in 3.x?

I suspect there are ways of lowering confusion over indices by using well-named intermediate variables. Perhaps something like:
```
idx1b =  linspace(6,10) 
idx = idx1b - BASE_CORRECTION
show_3D_array(image[idx,:,:])  
```
where `BASE_CORRECTION` is 1 in Python and 0 in MATLAB.

You should keep as much code as possible the same, but where is has to differ, be explicit.

**Comment by KrisThielemans** [comment]
Re-reading my original comment, I think I need to clarify this.

I would think there is no problem in having people pass an array to `show_3D_array` using "native" array manipulations (we can't stop them in any case). This is for instance used [here](https://github.com/CCPPETMR/SIRF/blob/163c3a6de58ca76d8167d94858fcdace898f352d/examples/Matlab/MR/Gadgetron/fully_sampled_recon_single_chain.m#L88) and [here](https://github.com/CCPPETMR/SIRF/blob/163c3a6de58ca76d8167d94858fcdace898f352d/examples/Python/MR/grappa_basic.py#L107) and [here](https://github.com/CCPPETMR/SIRF/blob/163c3a6de58ca76d8167d94858fcdace898f352d/examples/Python/PET/randoms_from_listmode.py#L118). By the way, it is hardly used in the MATLAB demos.

Instead, my comment was about the use of non-standard strings to specify indices. It's something that nobody will expect, and it turns out we're not using it. So, as opposed to trying to decide on making this uniform between MATLAB and Python, I vote to remove it.

I guess another question is what label to use in the figure that is displayed. We're currently using 1-based labels in both. I don't have a strong opinion on that.

**Comment by KrisThielemans** [comment]
> 1-based indexing in Python would mean that indexing on image and on image.as_array() would be inconsistent, potentially confusing.

good point! I think that holds for labelling as well. That seems to say we have to stick to 0-based in Python everywhere.

@evgueni-ovtchinnikov, can you therefore please remove the string-based facility, change the Python labels, update the doc, and somewhere in the UserGuide add a statement about indexing for Matlab and Python (that we use "native" convention for ordering and offset, and that this means that this is a place where Matlab and Python SIRF code diverges. Possibly best to add an explicit example.)

**Comment by KrisThielemans** [comment]
I guess the 'index' keyword can just accept a list/tuple/array of ints as well.

Obviously, this change will need to be in CHANGES.md (put it in the same commit) and a separate email sent to the developers as it's another backwards-compatibility-breaking change.

**Comment by paskino** [comment]
IMO we must adopt the indexing dictated by the language we target rather than making the interface of SIRF uniform between Python and MATLAB, as it is absolutely confusing.

For what regards indexing in Python I think we should adopt the conventions of Numpy. 

That funky type of indexing could be developed as named method rather than overriding the indexing method.

**Comment by DANAJK** [comment]
My suggestion was not that Python users use 1b indexing, but there is a mechanism provided to go from what the user is using to the native base, and, that the user's code is clear. This could be helpful when translating code between MATLAB and Python because the code would only differ between MATLAB and Python where you convert from whatever base you have chosen to the native base. In my example, the variable `BASE_CORRECTION` might have been better named `decr1btonative` to highlight it is a decrement from 1b to native (as in my example the user had chosen to specify the indices in 1b). 

The complexity is forced upon us by external factors, so it is good to introduce the complexity at this point in the code -  it forces the coder and anyone reading the code to think about the issue at the point where it is relevant. 

The question about image labelling is really about what is your default image coordinate system. The MATLAB mapping from array indices to default image coordinates is at least well documented. 

For index ordering, I think there are two issues:
 1) the mapping from array to image coordinates (is the first dimension rows or columns?)
 2) the implicit quantity that dimension holds (the first dimension could be channels or readout samples or phase encode number), if this information was stored, it might be easier, and would address the issue of the other 40+ dimensions.

I  don't see an easy answer to the ordering, one option would be to provide a function that returned the indices to use.

**Comment by paskino** [comment]
IMO indexing should be consistent with the target language, otherwise it's very confusing. In Python we should follow Numpy's.

**Comment by KrisThielemans** [comment]
this last comment is about user input in `show`, not directly about `show_3D_array` of course. It is relevant here as `show` uses `show_3D_array`, see [here](https://github.com/CCPPETMR/SIRF/blob/862778610f6ccf7ecaaa8f150ea6c4a8f94c76cb/src/xSTIR/pSTIR/STIR.py#L558).

I guess it'd be confusing to have user-interaction be different from indices used for a function call, so my feeling is that in Python, this still has to be 0-based. (probably best to make that explicit in the `print` statement).

The question about the `eval` is because `show` wants to be able to ask the user for input before calling `show_3D_array` (if no slice is specified). I wonder if this isn't just creating trouble for ourselves. I vote for removing the "ask the user which slices" bit of `show`, and just  show all slices if no argument is passed, or call `show_3D_array` if more than 1 index is given, or `show_2D_array` if there is only 1.
