### ISSUE TITLE
improvements for "coil_combination.py"

### ISSUE THREAD

**Issue by mehrhardt** [CCPPETMR/SIRF#187]
I noticed a few small things in the aforementioned file that I would like to mention.

1) `k_array = k_array[0:256,:,:]` Why do we throw away half of the data here? Is this a recommendation how people would handle real data?

2) `image_array = image_array/image_array.max()` First, `image_array.max()` is a complex number (in this example `(0.0065700701233406926-0.002452717861789599j)`), thus we change both the magnitude and the phase of the complex image. I suppose this is just for visualization and we look only at the magnitude. Therefore, I would rescale by the largest magnitude `image_array = image_array/abs(image_array).max()`.

3) Again in the line `image_array = image_array/image_array.max()`. As this is a small example, nothing really matters here in terms of efficiency. However, users might copy this example to work on their real large scale data. Thus, I would change this line to `image_array /= image_array.max()` in order to avoid an extra copy and also speed up the computations.

4) `ax.imshow(abs(image_array_sos-image_array_ws), vmin=-0, vmax=0.1)` Why do we use '-0'?

5) Does the python part of SIRF follow a specific style? I did notice that it does not follow PEP8 which is a common style guide for python.

**Comment by ckolbPTB** [comment]
Regarding your comments:
1. This dataset contains two times the same raw data called repetitions. Because it is the same data and to make it easier to visualise, we only use the first repetition. (For real applications of course each repetition would not be exactly the same and they could be averaged to improve SNR).

2.+3.+4. Yes you are right about these points. Feel free to ammend the file.

5. Which lines do not follow PEP8? We tried to follow the standard but maybe we missed a few things...
