### ISSUE TITLE
Python users expect * to act elementwise on vectors

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#190]
At present, x*y for vector-like x and y stands for the inner product of x and (conjugate of, in complex case) y.

However, most Python users would expect * to stand for elementwise multiplication.

Therefore, * should better be redefined elementwise, and x.dot(y) should be used for the inner product.

**Comment by evgueni-ovtchinnikov** [comment]
replaced x*y with x.dot(y) in python scripts

**Comment by KrisThielemans** [comment]
I guess `dot(x,y)` would be more natural (and how it's done in numpy). Of course, `x.dot` is a method of `x` which is what you want. Not sure how this would be done in Python (aside from define `sirf.dot(a,b)` to be `a.dot(b)`, but that's maybe unsafe?

**Comment by evgueni-ovtchinnikov** [comment]
overloaded * and / as elementwise operations in python

same for .* and ./ in matlab

**Comment by DANAJK** [comment]
Overloading native operations might be confusing - does it only apply to SIRF objects within a script?
I would favour using explicit methods such as `dot`  (scalar product of vectors), `cross` (vector product of vectors), `times` (element-by-element vector multiplication) and `mtimes` (matrix multiplication).

**Comment by KrisThielemans** [comment]
I'll disagree there. Overloading with native operators is exactly what you want to do. The SIRF objects should act as much like native objects would do. That causes least surprises for the Python user, and will also increase likelihood of being able to use other Python packages. We can duplicate with explicit methods of course.

Same for Matlab of course.

**Comment by DANAJK** [comment]
I had mis-understood what you are planning and agree that within a script, a shortcut operation such as * should do the same thing for native and SIRF objects. Nevertheless, changing meanings of SIRF shortcuts depending on language will make any translation between Python and MATLAB confusing. So, unless it causes memory or efficieny problems, it is likely to be better if we prevent the use of shortcuts such as *, .* etc on SIRF objects and force the use of explicit methods.    

One point that can be confusing in MATLAB is that since R2016b it has performed implicit expansion. For example `row_vec .* col_vec` is not an error and returns a matrix. For a more complete discussion see: [https://nickhigham.wordpress.com/2016/09/20/implicit-expansion-matlab-r2016b/](https://nickhigham.wordpress.com/2016/09/20/implicit-expansion-matlab-r2016b/)

**Comment by ashgillman** [comment]
Numpy will do the same, but they call it broadcasting
```
In [10]: np.arange(5).reshape((1, 5)) * np.arange(5).reshape((5, 1))                                                                                                                                 
Out[10]: 
array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])
```

It is a little tricky for conversion, but Python's `@` is most like MATLAB's `*`, and Python's `*` is most like MATLAB's `.*`.
