### ISSUE TITLE
submodule fixes and documentation

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#219]
Based on discussion:

- [x] 1. SIRF: create a new commit on top of master to point the submodule to CCPPETMR/SIRF_data@cd139a1c69fafb0b2126495d8716c0ee3e38c9dd
    * fixed by https://github.com/CCPPETMR/SIRF/commit/2c8dbb2b2fd9eb95da8ff46bcc38d3956721313d
- [x] 2. Remove the last commit CCPPETMR/SIRF_data@09ca932ed027af3567d06fc47855b2a0d0ca7e7d, force push
- [x] 3. Document ~~somewhere~~ (~~either [wiki](https://github.com/CCPPETMR/SIRF/wiki) or~~ [CONTRIBUTING.md](https://github.com/CCPPETMR/SIRF/blob/master/CONTRIBUTING.md)~~?~~)
- [x] 4. Merge master to devel (?)
- [x] 5. Write an email to the devel list.

**Comment by KrisThielemans** [comment]
Unfortunately, the SIRF master and devel branches are again using the wrong submodule commit (i.e. the one that was removed).

Root cause is as follows:
- @casperdcl removed the top commit in data as requested, force pushed to github
- @evgueni-ovtchinnikov pulls, include submodule update. This effectively pulls the data submodule (syncing his `origin/data` to the github version)
- @evgueni-ovtchinnikov `data` now claims it's one commit ahead of `origin`. Indeed, it didn't remove the top commit from the local copy.
- @evgueni-ovtchinnikov does a `git status` in `SIRF` and sees that the `data` submodule isn't up-to-date, so commits it (putting the submodule back to the (removed) top commit.

We tried to remove the data folder completely, and redo the `pull -recurse-submodules', but that didn't help (which I really don't understand).

I've now repeated step 1 (commit 1abbd60eb60dab44be67ed3c49512050552a8213).

@casperdcl, how does @evgueni-ovtchinnikov (and everyone else with this problem) fix his local clone(s)?

**Comment by ashgillman** [comment]
Git checkout master
Git reset --hard origin/master

Ash
Sent from mobile

On 1 Nov. 2018 08:14, Kris Thielemans <notifications@github.com> wrote:

Unfortunately, the SIRF master and devel branches are again using the wrong submodule commit (i.e. the one that was removed).

Root cause is as follows:

  *   @casperdcl<https://github.com/casperdcl> removed the top commit in data as requested, force pushed to github
  *   @evgueni-ovtchinnikov<https://github.com/evgueni-ovtchinnikov> pulls, include submodule update. This effectively pulls the data submodule (syncing his origin/data to the github version)
  *   @evgueni-ovtchinnikov<https://github.com/evgueni-ovtchinnikov> data now claims it's one commit ahead of origin. Indeed, it didn't remove the top commit from the local copy.
  *   @evgueni-ovtchinnikov<https://github.com/evgueni-ovtchinnikov> does a git status in SIRF and sees that the data submodule isn't up-to-date, so commits it (putting the submodule back to the (removed) top commit.

We tried to remove the data folder completely, and redo the `pull -recurse-submodules', but that didn't help (which I really don't understand).

I've now repeated step 1 (commit 1abbd60<https://github.com/CCPPETMR/SIRF/commit/1abbd60eb60dab44be67ed3c49512050552a8213>).

@casperdcl<https://github.com/casperdcl>, how does @evgueni-ovtchinnikov<https://github.com/evgueni-ovtchinnikov> (and everyone else with this problem) fix his local clone(s)?

**Comment by ashgillman** [comment]
Sorry, email formatting obviously doesnt work well.

To undo the last commit:

```
git checkout master
git reset --hard HEAD~
```

The Tilda means back one. Then push up, but be very careful with force push

```
git log --graph # check this is what you want
git push --force origin master
```

Then, until another commit is pushed, others will have to

```
git fetch origin
git checkout master
git reset --hard origin/master # move local master to origin/master
```

**Comment by ashgillman** [comment]
Actually, it might be safer to revert the change (this adds an additional 'negative' diff) than to reset it. I don't know the command by heart but Google does.

**Comment by ashgillman** [comment]
Ah I see.

So @evgueni-ovtchinnikov has commits on top of the old master?

So then he could rebase. @evgueni-ovtchinnikov, see https://dev.to/blakedeboer/beginners-guide-to-interactive-rebasing-1ob

You would essentially run `git rebase -i <hash of the commit before the one you want gone>`, and then in the editor that should pop up, just delete the line with the commit to remove. This will then effectively rerun all the commits and changes, omitting that one.

**Comment by ashgillman** [comment]
If anyone else has pulled the wrong commit, then if they make a PR it would try to merge the change back in, but it could only sneak back in via a merge once there are commits on top of the "missing" commit. If this happens, whoever is trying to merge can use the same rebase trick to omit that commit from their branch.

**Comment by KrisThielemans** [comment]
> So @evgueni-ovtchinnikov has commits on top of the old master?

yes.

The rebasing stuff is way too scary for most. At first sight, I see nothing wrong with telling affected people to do what you suggest above
```sh
cd SIRF/data
git fetch origin
git checkout master
git reset --hard origin/master # move local master to origin/master
cd ..
```
However, I see then that their local `data` will point to `origin/master` (of course), as opposed to the usual case where it points to the detached HEAD for the relevant commit. I don't know if this has consequences down the line.

**Comment by casperdcl** [comment]
Erm.

```bash
cd data && git fetch origin && git reset --hard origin/master
```

**Comment by casperdcl** [comment]
no, no consequences

**Comment by KrisThielemans** [comment]
great.

@evgueni-ovtchinnikov , can you please try
```
cd data && git fetch origin && git reset --hard origin/master 
cd ..
git checkout master
git pull --resucrse-submodules
git status
```
and confirm that all is well?

**Comment by evgueni-ovtchinnikov** [comment]
done, branch is now 'up-to-date with origin/master' - thanks!!!

**Comment by KrisThielemans** [comment]
great. @casperdcl, feel like doing a PR for the `.gitignore` change + some extra doc in CONTRIBUTING.md?

**Comment by casperdcl** [comment]
k's will do
