### ISSUE TITLE
running Gadgetron multiple times concatenates images

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#273]
found by @DANAJK and @rijobro 

not sure what to do with this. should at least put it in the doc, or generate a warning, ideally remove existing file first.

@evgueni-ovtchinnikov please decide on what's feasible and possibly just do the minimum, then assign the rest to a future milestone.

**Comment by DANAJK** [comment]
To be more precise, gadgetron appends a new recon to the hdf5 output file if it exists. It doesn't concatenate images. Usually each new recon has a dataset name that contains the date and time so that they can be distinguished. Think of hdf5 more like a file system than a single file. 
So, I have a suspicion that the mis-leading aspect of this is coming from either the way we read the hdf5, or how the txt file was generated.

**Comment by rijobro** [comment]
We allow the user to choose any name for the dataset. I was using the same name each time, so they were getting concatenated. Does this mean we should remove the possibility of choosing names for datasets, and just use a string from the current date/time?

**Comment by rijobro** [comment]
closed via #285
