### ISSUE TITLE
fix coveralls and codecov

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#320]
See comments in https://github.com/CCPPETMR/SIRF/pull/318

**Comment by casperdcl** [comment]
Coverage being reported for installed files (which have different paths to source files).

- https://bitbucket.org/ned/coveragepy/pull-requests/70/set-base-directory-for-relative-filenames/activity# (mentioning [paths]).
- lemurheavy/coveralls-public#263
- or can go back to running tests from sources/SIRF rather than INSTALL/python?
- or could find&replace paths in the generated coverage reports before uploading?
