### ISSUE TITLE
disable Reg if NiftyReg not found

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#352]
currently errors out

**Comment by rijobro** [comment]
I've updated NiftyReg https://github.com/KCL-BMEIS/niftyreg/pull/51, which means that we can do away with the troublesome `FindNiftyReg.cmake` files that were in SIRF and the Superbuild. Now users can give the directory containing `NiftyRegConfig.cmake` and everything should work.

However, I'm a tiny bit stuck on how to update both SIRF and the Superbuild whilst keeping CI happy (and allowing for backwards compatibility?)...

1. I want to delete `FindNiftyReg.cmake` from both SIRF and the Superbuild
2. Instead of passing the variable `NiftyReg_Binary_DIR` from Superbuild to SIRF, I want to use `NIFTYREG_DIR`
3. In SIRF, I want to be able to use the `NiftyRegConfig.cmake`, as per https://github.com/rijobro/SIRF/tree/fix_niftyreg

However, testing SIRF requires on Superbuild and vice versa, so i'm not sure how to update one then the other.
