### ISSUE TITLE
Python/PET/interactive demos fail on VM

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#370]
The script `display_and_projection.py` runs ok, but subsequent running of any of the rest fail.

In Spyder (started from shell), running further scripts in the same console produces error messages suggesting that `pystir` is `None`, whereas running them in a separate dedicated console produces error message 'name pet is not defined'.

Richard checked that they also fail in IPython run in a terminal, so it is not a Spyder problem.

**Comment by paskino** [comment]
There are a few problems here:

1. the interactive scripts are meant to be executed in a specific order (in spyder) but the order is not so apparent and I suggest to change the name of the file to have `01_display_and_projection.py` and so forth
2. `display_and_projection.py` does not display any image if run as a whole script. If you run the cells then the images are plotted and everything seems fine.
3. the scripts redefine [`slice`](https://docs.python.org/3/library/functions.html#slice) function
4.  `basic_reconstruction.py` tries to display the slice 5 which is uniformly 0
5. in `reconstruction.py` both `acquisition_array` and `noisy_array` have 4D so the display at [these lines](https://github.com/CCPPETMR/SIRF/blob/master/examples/Python/PET/interactive/reconstruction.py#L167L169) fail. [Other plots](https://github.com/CCPPETMR/SIRF/blob/master/examples/Python/PET/interactive/reconstruction.py#L183L185) fail because of the size of the array passed to `imshow`

**Comment by paskino** [comment]
According to the [README](https://github.com/CCPPETMR/SIRF/blob/pet_interactive_example/examples/Python/PET/interactive/README.md) the scripts should be run cell-by-cell.
