### ISSUE TITLE
require STIR 4.0.0

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#460]
in CMakeLists.txt. will need to also update SIRF-SuperBuild version_config.cmake

**Comment by rijobro** [comment]
This probably shouldn't have been done until STIR 4 has been released. Until STIR 4 does exist, `find_package(STIR 4.0.0 REQUIRED)` is impossible so SIRF build will always fail. 

I would suggest we revert #460 until STIR 4 is out. @KrisThielemans ? (Also, what's wrong with people using current SIRF with STIR 3.1? The versions are **mostly** compatible, right?)

**Comment by KrisThielemans** [comment]
STIR has already updated its version number, even if it isn't tagged yet.

@evgueni-ovtchinnikov  first changed the `version_config.cmake` in the SuperBuild, then this one. When STIR is released, we change the `version_config.cmake` again.

I cannot quite remember when we set STIR's version number to STIR 3.1. There's been changes since then which probably change SIRF. I prefer to be safe therefore.
