### ISSUE TITLE
Matlab tests on master currently failing

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#76]
I'm getting an error when running `ctest -VV` for SIRF master on the UCL CS CentOS system.
Just running `test1` by hand shows
```
bash-4.2$ $SIRF_MATLAB_EXECUTABLE -nojvm -nodesktop -r test1

                            < M A T L A B (R) >
                  Copyright 1984-2017 The MathWorks, Inc.
                   R2017a (9.2.0.556344) 64-bit (glnxa64)
                               March 27, 2017

 
For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
loading miutilities library...
loading mgadgetron library...
+++ test 1 passed
Segmentation fault
```

**Comment by KrisThielemans** [comment]
This is apparently caused by incompatible compiler and MATLAB. @evgueni-ovtchinnikov  to confirm

**Comment by evgueni-ovtchinnikov** [comment]
I cannot use SuperBuild on UCL Linux machines because they have CMake 3.5.1, so cannot confirm.

ctest -VV in ~/devel/build/SIRF works ok, so must be a SuperBuild issue.

**Comment by KrisThielemans** [comment]
On UCL CS Linux systems, use `/slms/inm/research/tools/bin/cmake`.

As we suspect this depends on compiler version and MATLAB version, we'll have to check that. I was using ` Matlab_ROOT_DIR=/cs/sys/software0/Matlab/matlab-R2017a ` and the default compiler, which turns out to be gcc 4.8.5 20150623.
`

**Comment by evgueni-ovtchinnikov** [comment]
Thanks, can cmake now!

Got this error though:

Cloning into 'SIRF'...
Checking out files: 100% (240/240), done.
Switched to a new branch 'devel'
Branch devel set up to track remote branch devel from origin.
Submodule 'data' (https://github.com/CCPPETMR/SIRF_data.git) registered for path 'data'
Cloning into 'data'...
fatal: reference is not a tree: 3f0650018cfeb86be4c9ec6b6ae3fe1b2045a5c3
Unable to checkout '3f0650018cfeb86be4c9ec6b6ae3fe1b2045a5c3' in submodule path 'data'
CMake Error at SIRF-prefix/tmp/SIRF-gitclone.cmake:83 (message):
  Failed to update submodules in:
  '/cs/research/external/home/eovtchin/devel/SIRF-SuperBuild/SIRF'

make[2]: *** [SIRF-prefix/src/SIRF-stamp/SIRF-download] Error 1
make[1]: *** [CMakeFiles/SIRF.dir/all] Error 2
make: *** [all] Error 2

I tried to copy data from SIRF, but it gets deleted when I run make, and I get the same error message.

Why on earth running make clones SIRF instead of pulling?

**Comment by KrisThielemans** [comment]
This seems to be because on the devel branch you refer to a hash for the data submodule that doesn't exist on github. I have the same by just doing in SIRF `git checkout devel;git pull;git submodule update`. I suspect you didn't push your changes in the submodule. 
```
cd SIRF/data
git push
```
Submodules are tricky...

**Comment by evgueni-ovtchinnikov** [comment]
I turned out - I did not! Thanks a lot for spotting this.

Now I am out of disk quota...

**Comment by evgueni-ovtchinnikov** [comment]
I built SIRF using SIRF-SuperBuild on /slms, but Matlab apparently was not found by CMake as ctest only runs Python tests

**Comment by evgueni-ovtchinnikov** [comment]
on murchison matlab-R2017a fails with error messages GLIBCXX_3.4.20 not found and CXXABI_1.3.8 not found, R2015b and R2014b work ok

**Comment by KrisThielemans** [comment]
ok. this is an unrelated issue then with MATLAB compatible compilers etc. So closing this.
